branches:
  master:
    regex: ^dev(elop)?(ment)?$
    tag: ''
    increment: Minor
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
    tracks-release-branches: true
    is-release-branch: false
    is-mainline: true
  feature:
    regex: features?[/-]
    tag: 'useBranchName'
    increment: Minor
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
    tracks-release-branches: true
    is-release-branch: false
    source-branches: ['master','release','feature','hotfix']
  release:
    regex: releases?[/-]
    tag: ''
    increment: Major
    prevent-increment-of-merged-branch-version: true
    track-merge-target: true
    tracks-release-branches: false
    is-release-branch: true
    source-branches: ['master']
  hotfix:
    regex: hotfix(es)?[/-]
    tag: 'hotfix-{BranchName}'
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: true
    tracks-release-branches: false
    is-release-branch: false
    source-branches: ['release']
ignore:
  sha: []
merge-message-formats: {}
